# branches to build
branches:
  # whitelist
  only:
    - master

image: Visual Studio 2017

configuration: Release

before_build:
  - nuget restore SharpFontWrapper-Samples.sln

build:
  project: appveyor.targets

artifacts:
  # pushing a single file
  - path: build/Zip/SharpFontWrapper.zip
    name: SharpFontWrapper

